version: '3'

services:
  makemigrations:
    image: service:last
    command: "python manage.py makemigrations"
    environment:
      DJANGO_SETTINGS_MODULE: tom_project.settings
    volumes:
      - ./tom_project:/opt/project

  migrate:
    image: service:last
    command: "python manage.py migrate"
    environment:
      DJANGO_SETTINGS_MODULE: tom_project.settings

  test:
    image: service:last
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "python manage.py test calculator"
    environment:
      DJANGO_SETTINGS_MODULE: tom_project.settings

  fill_db:
    image: service:last
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "python manage.py shell < fill_db.py"
    environment:
      DJANGO_SETTINGS_MODULE: tom_project.settings
