# Generated by Django 3.2 on 2021-04-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
                'ordering': ('-cost',),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('state_code', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(default='', max_length=30)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
                'db_table': 'state_taxes',
                'ordering': ('state_code',),
            },
        ),
    ]
